### ISSUE TITLE
Create users using a command/non interactive way of creating a user

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo#196]
This would be nice for the purpose of automation

**Comment by AliSayyah** [comment]
@dantownsend  I want to add this feature if it's ok. but I think this functionality should be added to 'targ', right?

**Comment by dantownsend** [comment]
@AliSayyah I think we can do it by modifying this function in the Piccolo repo:

https://github.com/piccolo-orm/piccolo/blob/ccdabaa341c317180659b665cecb763aba3a8873/piccolo/apps/user/commands/create.py#L58

So would be something like:

```python
def create(
    username: t.Optional[str] = None,
    email: t.Optional[str] = None,
    password: t.Optional[str] = None,
    is_admin: t.Optional[bool] = None,
    is_superuser: t.Optional[bool] = None,
    is_active: t.Optional[bool] = None
):
    """
    Create a new user.
    """
    username = get_username() if username is None
    email = get_email()  if email is None

    if password is None:
        password = get_password()
        confirmed_password = get_confirmed_password()
        
        if not password == confirmed_password:
            sys.exit("Passwords don't match!")

    is_admin = get_is_admin() if is_admin is None
    is_superuser = get_is_superuser() if is_superuser is None
    is_active = get_is_active() if is_active is None
    
    ...
```

So shouldn't be too bad of a change - just need to modify the unit tests for it, and make sure it works. If you're happy to give it a go, that would be great. Otherwise I can make the change.

Hopefully it will work without any changes to targ.

**Comment by AliSayyah** [comment]
thank you for your feedback.
I will make the necessary changes and fix the tests.

**Comment by dantownsend** [comment]
@AliSayyah Great, thanks. If you need any help let me know.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo/pull/231
