### ISSUE TITLE
Using asyncio.gather raises TypeError

### ISSUE THREAD

**Issue by brnosouza** [piccolo-orm/piccolo#358]
When using asyncio.gather with any query instance, Insert for example, it raises a TypeError

```
TypeError: unhashable type: 'Insert'
```

Does something changed? Because I remember this was working in a few versions ago. I'm using python 3.9/3.10

A workaround for now is to manually for-loop the queries

**Comment by dantownsend** [comment]
@brnosouza You're right, that's very odd.

I had a look, and it seemed like only some query types weren't working with `asyncio.gather`.

The ones which weren't working were dataclasses. There was no need for them to be dataclasses anymore, so now they're plain classes and they seem to work.

It looks like there's some weird behaviour around hashing dataclasses, which is why the `TypeError` was being raised.

**Comment by brnosouza** [comment]
thanks @dantownsend

**Comment by dantownsend** [comment]
@brnosouza It's on PyPI now version 0.60.2 - hopefully it fixes your issue. Thanks.
