### ISSUE TITLE
[Migration] - Updating a column value using column values in piccolo migration 

### ISSUE THREAD

**Issue by rathourarv** [piccolo-orm/piccolo#371]
We have a table Person with name and their date of birth. 

`class Person(Table):
    id = Serial()
    name = Varchar()
    date_of_birth = Date()
`

We need to add the column age on the same table now. We need to populate the age for existing entries using dob. I want to write a migration for it where I can add the age using their date of birth.

`async def forwards():
    manager = MigrationManager(
        migration_id=ID, app_name="app", description=DESCRIPTION
    )

    def run():
        Person.update({
            Person.age: now() - Person.date_of_birth
        }).run_sync()

    manager.add_raw(run)

    return manager`

Is it the right way to do it? The doc says, Never import your tables directly into a migration, and run methods on them.

**Comment by dantownsend** [comment]
@rathourarv The reason the docs say never to import a table class within a migration file is because the table class might get deleted in future. The migration would no longer run, as the import would fail.

It's best to keep your migration files as self contained as possible.

If you're pretty confident that the table class would never get deleted (in your example, `Person`), then it's OK.

Alternatively, you might consider redefining the ``Person`` class within your migration, so it's self contained. For example:

```python
from piccolo.apps.migrations.auto import MigrationManager
from piccolo.table import Table


ID = "2021-12-06T10:39:11"
VERSION = "0.61.1"


class Person(Table):
    date_of_birth = Date()
    age = Integer()


def run():
    Person.update({
        Person.age: now() - Person.date_of_birth
    }).run_sync()

async def forwards():
    manager = MigrationManager(migration_id=ID, app_name="concept_map")
    manager.add_raw(run)
    return manager
```

I hope that's useful.

**Comment by dantownsend** [comment]
Closing this issue for now. I'll update the docs on migrations at some point.

**Comment by rathourarv** [comment]
Thanks! It was helpful. 

One question, If I move the Person class to migration then how should we update the model if we want to add a new column in the future to this Person table?

**Comment by dantownsend** [comment]
@rathourarv You would still keep the `Person` class in your tables.py file.

The one in the migration file is just a copy of it, so the migration file is self contained, and doesn't have to import anything which may be deleted in the future.

I hope that makes sense - it's quite tricky to explain.
