### ISSUE TITLE
Problem when add BaseUser to existing table

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo#390]
I ran to a problem when I want to add `BaseUser` to an existing table (e.g. in the default Task app) after using `piccolo migrations  forwards user`. If I want to add new colum like this
```python
from piccolo.apps.user.tables import BaseUser
from piccolo.table import Table
from piccolo.columns import Varchar, Boolean, ForeignKey


class Task(Table):
    """
    An example table.
    """

    name = Varchar()
    completed = Boolean(default=False)
    task_user = ForeignKey(BaseUser) <= new column
```
I got the error `relation "piccolo_user" already exists`. If I don't run `piccolo migrations forwards user`, everything is fine and I can add BaseUser to the existing table. If I create a new application with `piccolo asgi new` and run only `piccolo migrations forwards session_auth` without `piccolo migrations forwards user`, everything is fine and I can add `BaseUser` to the existing table, can create a user (there is a warning that 3 migrations have not started - the app may not behave as expected) and the `piccolo_user` table is in admin.
I don't remember how I did it before, but not running a user app migration solves the problem. If there is another way, it would be good to add it to the docs to make users aware of it. Thanks.

**Comment by dantownsend** [comment]
@sinisaos I think the problem is when you look at the `piccolo_app.py` file generated by `piccolo asgi new`, it uses `table_finder`.

It will be importing all `Table` classes from `table.py`, including `BaseUser`. When you create a migration file to add the `task_user` column, it is probably also trying to recreate `BaseUser`.

The way I get around this is using tags.

```python
class Task(Table, tags=['tasks']):
    ...
```
Then `table_finder` becomes: `table_finder(['home.tables'], include_tags=['tasks'])`.

Another solution is to use `LazyTableReference` for the `ForeignKey`, rather than directly importing `BaseUser`:

```python
task_user = ForeignKey(LazyTableReference("BaseUser", module_path="piccolo.apps.user.tables"))
```
I could add a new option to `table_finder` which automatically excludes any `Table` classes not defined in that file. Something like this maybe:

```python
table_finder(['home.tables'], exclude_imported=True)
```

What do you think?
