### ISSUE TITLE
Rename column causes persistent rename column prompt in migration manager

### ISSUE THREAD

**Issue by theelderbeever** [piccolo-orm/piccolo#417]
If you rename a column in a Table and auto generate a migration you will be asked if you renamed a column. Answering "Y" and running the migration gives you the correct behavior. However, on subsequent migrations you are asked about the exact same column again. Also note that when renaming multiple columns answering "N" to the first prompt stops further ones. Additionally, The name pairings in the prompt aren't matched up properly.

This can be demonstrated using the basic asgi scaffold.

To get started...
```console
> piccolo asgi new
> piccolo migrations new home --auto
> piccolo migrations forwards home
```

- Then go to `./home/tables.py` and change the `completed` columns to `success` or anything other name.
- Another migration which will run fine
```console
> piccolo migrations new home --auto
Creating new migration ...
Did you rename the `completed` column to `success` on the `Task` table? (y/N)
> y
> piccolo migrations forwards home
```
Now go update the table again. I just added a `completed_at = Timestamptz` for ease.
Migrations again which produces and identical prompting about the previous rename.
```console
> piccolo migrations new home --auto
Creating new migration ...
Did you rename the `completed` column to `success` on the `Task` table? (y/N)
> n
> piccolo migrations forwards home
```
This results in an add_column/drop_column in the latest migration which is problematic.

**Comment by dantownsend** [comment]
@theelderbeever I'll investigate - the migrations shouldn't keep asking you if you renamed a column. There could be a bug.

**Comment by dantownsend** [comment]
@sinisaos Can you help me with this if you get the chance? Can you try recreating this bug?

**Comment by sinisaos** [comment]
@dantownsend Of course. I'll try recreating this bug and reporting result here.

**Comment by sinisaos** [comment]
@dantownsend I can recreate this bug. @theelderbeever is right. If we choose either `y` or `n` Piccolo always change the column and it is not correct. The problem is probably here https://github.com/piccolo-orm/piccolo/blob/0eb325f3083bac50e6241d6df3d04fe3dc095cf6/piccolo/apps/migrations/auto/schema_differ.py#L82

**Comment by dantownsend** [comment]
@sinisaos Thanks for looking into it. I can also replicate it.

When it asks 'did you rename?' - if I answer 'n', then it drops the old column and creates the new one, which is correct.

If I answer 'y', it creates a rename operation, which does get applied to the database.

However, the next time I try and create an auto migration, Piccolo doesn't seem to realise that the column was renamed.

I managed to work out what the issue is. We added a feature a couple of months ago called `db_column_name`:

```python
class MyTable(Table):
    class_ = Varchar(db_column_name="class")  # It allows us to map to column names which are problematic
```
There's a bug in migrations because of this. I don't know how I haven't encountered it sooner - I must not rename many columns! I'll push a fix soon. Obviously there's a hole in our test coverage for migrations too which needs improving.

**Comment by dantownsend** [comment]
As pointed out by @theelderbeever there is also an issue when trying to rename multiple columns in one go.

In this scenario:

```python
class MyTable(Table):
    a1 = Varchar()
    a2 = Varchar()
```

If we update it to:

```python
class MyTable(Table):
    b1 = Varchar()
    b2 = Varchar()
```

Then just asking `did you rename a1?` is insufficient, because a1 could now be `b1` OR `b2`.

We might need multiple user prompts:

```
Did you rename a1 to b1?
Did you rename a1 to b2?
Did you rename a2 to b1?
Did you rename a2 to b2?
```

If you have a lot of renamed columns, that's a lot of user prompts!

The prompt could be:

```
Was a1 renamed? Enter b1, b2, or n
Was a2 renamed? Enter b1, b2, or n
```

Thoughts?

**Comment by dantownsend** [comment]
There's a version of PyPI now which partially fixes this issue (0.69.1).

Just need to figure out a solution for when multiple columns are renamed in a single migration.

**Comment by sinisaos** [comment]
> ```
> Was a1 renamed? Enter b1, b2, or n
> Was a2 renamed? Enter b1, b2, or n
> ```
> 
> Thoughts?

This solution would be great.

**Comment by dantownsend** [comment]
This should be fixed now - thanks.
