### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by worldofgeese** [piccolo-orm/piccolo#476]
Any chance of supporting CockroachDB? I have a Flask project I'd like to use Piccolo in.

**Comment by sinisaos** [comment]
@dantownsend I've never used CockroachDB and I don't know if this is relevant but I managed to connect to the database with `PostgresEngine` like this
```python
DB = PostgresEngine(
    config={
        "database": "taskdb",
        "user": "root",
        "password": "",
        "host": "localhost",
        "port": 26257,
    }
)
```
I had to remove the `uuid-ossp` from [this line](https://github.com/piccolo-orm/piccolo/blob/d01066002e9932ff7b7ea7e2e678b8a54faf666c/piccolo/engine/postgres.py#L248) because this extension is not currently supported in CockroachDB (uuid will not work but this could to be [workaround](https://www.cockroachlabs.com/docs/stable/uuid.html) with `gen_random_uuid()`). Also `timestamptz` does not work so no migration can be done for `session_auth` (possible [workoround](https://github.com/cockroachdb/cockroach/issues/43179)). 
Standard columns work and I could do migrations for user table and task table and after that I could add records to that tables. 
This is a screenshot from a very nice Cockroachdb web console.

![cockroach_console](https://user-images.githubusercontent.com/30960668/160984009-a8a788e9-8ed8-4ecc-bbce-812bbd1e70c2.png)

I’m not an expert but I think support for CockroachDB could be made without too many changes, but you’ll know better.

**Comment by dantownsend** [comment]
@sinisaos Thanks for looking into it - that's very helpful.

It seems like we could support CockroachDB without too many changes.

I assume that `Timestamptz` fails because the default value of `current_timestamp` isn't supported. This could be worked around.

How easy did you find it to install CockroachDB locally? We would also need to work out how to run it in GitHub Actions for our test suite.

**Comment by sinisaos** [comment]
> How easy did you find it to install CockroachDB locally? 

Local installation is quite simple ([linux](https://www.cockroachlabs.com/docs/v21.2/install-cockroachdb-linux), [mac](https://www.cockroachlabs.com/docs/v21.2/install-cockroachdb-mac)).
For my attempt, I launched an [insecure cluster](https://www.cockroachlabs.com/docs/v21.2/start-a-local-cluster), but a [secure cluster](https://www.cockroachlabs.com/docs/v21.2/secure-a-cluster) should not be difficult to manage.

>  We would also need to work out how to run it in GitHub Actions for our test suite.

For Github Actions I didinn't find any example.

**Comment by dantownsend** [comment]
@sinisaos Thanks, I'll try and get it running locally.

**Comment by dantownsend** [comment]
I think this is a cool idea, and is definitely possible. I won't be able to pick it up immediately though, so if anyone wants to take a look feel free.

**Comment by dantownsend** [comment]
We now have CockroachDB support in the latest version of Piccolo.
