### ISSUE TITLE
[Question] Creating a PostgresEngine fails when write access not provided for the db

### ISSUE THREAD

**Issue by dashsatish** [piccolo-orm/piccolo#494]
Hi,
We found when we declare an additional PostgresEngine apart from the convention `DB` variable . The extra db engine is also tried for `CREATE EXTENSION ...` which fails while setting up a db connection.

Failure:
=======
  File "/My/virtualenvs/foo-service-4N9uyHRW/lib/python3.10/site-packages/piccolo/engine/postgres.py", line 286, in __init__
    super().__init__()
  File "/My/virtualenvs/foo-service-4N9uyHRW/lib/python3.10/site-packages/piccolo/engine/base.py", line 28, in __init__
    run_sync(self.prep_database())
  File "/My/virtualenvs/foo-service-4N9uyHRW/lib/python3.10/site-packages/piccolo/utils/sync.py", line 25, in run_sync
    return loop.run_until_complete(coroutine)
....
File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.ReadOnlySQLTransactionError: cannot execute CREATE EXTENSION in a read-only transaction

Solution for now:
===============
We have supplied `extensions=[]` while declaring or defining the postgres engine.
Example:
REPLICA_DB: PostgresEngine = PostgresEngine(
    {
        "host": ENV_SETTINGS.db_read_replica_attributes[
            Constants.DATABASE_HOST_KEY
        ],
        "port": ENV_SETTINGS.db_read_replica_attributes[
            Constants.DATABASE_PORT_KEY
        ],
        "database": ENV_SETTINGS.db_read_replica_attributes[
            Constants.DATABASE_NAME_KEY
        ],
        "user": ENV_SETTINGS.db_read_replica_attributes[
            Constants.DATABASE_USER_KEY
        ],
        "password": ENV_SETTINGS.db_read_replica_attributes[
            Constants.DATABASE_PASSWORD_KEY
        ],
    },
    extensions=[],
)

**Comment by dantownsend** [comment]
@dashsatish Interesting - I'm guessing it's a read only database, which is why there's this problem.

You're right, setting extensions to `[]` is a workaround.

`PostgresEngine` could try detecting if it's in read only mode, but I don't know if there's a reliable way to do this.

I could add an attribute like `read_only` to `PostgresEngine`, so it knows not to try creating extensions.

I think the best solution though is just to add a new section to the docs, mentioning your workaround for read only databases.
