### ISSUE TITLE
Cannot create references to non-integer Foreign keys

### ISSUE THREAD

**Issue by scott2b** [piccolo-orm/piccolo#560]
Given a foreign key relationship like this:

```
class Owner(Table):
    owner_id = Varchar(length=128, primary_key=True)

class Thing(Table):
    owner = ForeignKey(Owner)
```

Then given an existing Owner object `owner`, both of the following will fail with "asyncpg.exceptions.DataError: invalid input for query argument ... ('str' object cannot be interpreted as an integer)"

```
await Thing.objects().create(owner=owner)
```

```
thing = Thing(owner=owner)
await thing.save()
```

**Comment by dantownsend** [comment]
That's a weird one. I tried it locally with this schema:

```python
from piccolo.table import Table
from piccolo.columns import Varchar, ForeignKey

class TableA(Table):
    pk = Varchar(length=128, primary_key=True)


class TableB(Table):
    table_a = ForeignKey(TableA)

>>> table_a = TableA.objects().create(pk='test').run_sync()
>>> TableB.objects().create(table_a=table_a).run_sync()
```

It seemed to be OK, but I'll play around with it some more.

There's a good chance the problem is due to migrations. Piccolo migrations don't handle changes in the primary key well (it's a tricky problem to change the type of an existing primary key). So if the primary key was originally a serial column, this might explain the problem. Double check the database, in case the primary key is still a serial.

**Comment by scott2b** [comment]
Good call. That's it. I have a previously run migration that changes the primary key, but I see that the original id field is still set as the primary key constraint in the database. I can work with this. Feel free to close this .. it seems more appropriately issued as the specific migration problem that is the root cause here.

Thank you!

**Comment by dantownsend** [comment]
Cool, thanks!
