### ISSUE TITLE
SQLite in "production"

### ISSUE THREAD

**Issue by eddyg** [piccolo-orm/piccolo#767]
On the [Database Support](https://piccolo-orm.readthedocs.io/en/latest/piccolo/getting_started/database_support.html) page, it says:

> Limited SQLite support is available, mostly to enable tooling like the playground. Postgres is the only database we recommend for use in production with Piccolo.

But on the [Supported Databases](https://piccolo-orm.readthedocs.io/en/latest/piccolo/features/supported_databases.html) page it says:

> SQLite support is not as complete as Postgres, but it is available - mostly because it’s easy to setup.

and then in the [Tutorials](https://piccolo-orm.readthedocs.io/en/latest/piccolo/tutorials/using_sqlite_and_asyncio_effectively.html) section there's a **Using SQLite and asyncio effectively** page.

So I'm a bit confused as to whether or not it's "OK" to use SQLite as the database engine for Piccolo. I've also been looking at PeeWee, which has great SQLite support. I've used SQLite extensively in the past, and found it to be a _very_ capable database, so am wondering why _"Postgres is the only database we recommend for use in production with Piccolo"_, and if you have any specific examples of the issues or concerns I should be on the lookout for when using Piccolo with SQLite.

Thanks for any insight!

**Comment by dantownsend** [comment]
When Piccolo started, SQLite was just for tools like the playground. But as time went on, I realised that quite a few people wanted to use it in the production, so we've added more and more SQLite support.

The SQLite and Postgres support is almost at parity, except for one major difference, and that's automatic database migrations. SQLite has really terrible `ALTER TABLE` support.

So rather than using migrations, either manually create the tables by hand in SQLite, or do something like this:

```python
class TableA(Table):
    name = Varchar()

class TableB(Table):
    name = Varchar()

from piccolo.table import create_db_tables

await create_db_tables(TableA, TableB, if_not_exists=True)
```

You're right that the docs need rewording - it's certainly possible to use SQLite in production now.

**Comment by eddyg** [comment]
Thanks for taking the time to reply!

I'm glad to hear support for SQLite in Piccolo is "right up there" with Postgres. I appreciate the warning about migrations and the helpful example (I know what a challenge "altering" a table in SQLite can be!)

Thanks again. 👍
